$Bug: Tuple crahes with runtime exception (when used in precondition)$
$Category: OCL$
$State: Closed$
$BugAuthor: mk$
$Tests: test/t042$

DESCRIPTION:

  model TupleCrash

  class tuple_crash
  attributes
    a:Tuple(one:Set(Tuple(x:Integer,y:Integer)),
	    two:Set(Tuple(z:Integer,w:Integer)))
  operations
    op()
  end

  constraints

  context tuple_crash::op() pre fresh:
    -- true
    a.isUndefined()

  use> java.lang.RuntimeException: case 811 not handled
	  at org.tzi.use.parser.ocl.ASTOperationExpression.gen1(ASTOperationExpression.java:341)
	  at org.tzi.use.parser.ocl.ASTOperationExpression.gen(ASTOperationExpression.java:135)
	  at org.tzi.use.parser.use.ASTPrePostClause.gen(ASTPrePostClause.java:73)
	  at org.tzi.use.parser.use.ASTPrePost.gen(ASTPrePost.java:138)
	  at org.tzi.use.parser.use.ASTModel.gen(ASTModel.java:222)
	  at org.tzi.use.parser.use.USECompiler.compileSpecification(USECompiler.java:73)
	  at org.tzi.use.gui.main.MainWindow$ActionFileOpenSpec.compile(MainWindow.java:764)
  ...

SOLUTION: 

  Already corrected by earlier bug fixes for tuple types.
 

